TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: "SGD"
  STEPS: 1
  BETA: 0.9
  LR: 0.00025
  WD: 0.
  MOMENTUM: 0.9

INPUT:
  SIZE: (32, 32)

ADAPTER:
  NAME: PRDCL
  PRDCL:
    FISHER_ALPHA: 0.999
    CONSISTENCY: 3.0
    CONSISTENCY2: 3.0
